version: '3'
services:
  db:
    container_name: db
    restart: always
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_secure_password  # <-- Add this line
    networks:
      - db
  api:
    container_name: api
    depends_on:
      - db
    restart: always
    stop_signal: SIGINT
    image: akorn/scheduler
    ports:
      - 8080:8080
    environment:
      - DSN=postgres://postgres:your_secure_password@db:5432/postgres?sslmode=disable  # <-- Add password
    networks:
      - api
      - db
volumes:
  db:
    driver: local
networks:
  db:
  api:
